// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwsQjvt5b5OWkamLOWe55WhSr3uEPJ9dY',
    appId: '1:832641360790:web:42f37d3a37328407e833b7',
    messagingSenderId: '832641360790',
    projectId: 'possystem-64215',
    authDomain: 'possystem-64215.firebaseapp.com',
    storageBucket: 'possystem-64215.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeDMydIR4QkJzeQlofdpQ_NSiuWnlIDbk',
    appId: '1:832641360790:android:37bc0891951d4717e833b7',
    messagingSenderId: '832641360790',
    projectId: 'possystem-64215',
    storageBucket: 'possystem-64215.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4kKcxaml-ZRg6lPeQ1ZGVqpIeEo4siPM',
    appId: '1:832641360790:ios:b0b77d7b803d945de833b7',
    messagingSenderId: '832641360790',
    projectId: 'possystem-64215',
    storageBucket: 'possystem-64215.appspot.com',
    iosClientId: '832641360790-i3pv3uqh4q0tr22eriubmkej5610gh42.apps.googleusercontent.com',
    iosBundleId: 'com.example.croosflatformpos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4kKcxaml-ZRg6lPeQ1ZGVqpIeEo4siPM',
    appId: '1:832641360790:ios:b0b77d7b803d945de833b7',
    messagingSenderId: '832641360790',
    projectId: 'possystem-64215',
    storageBucket: 'possystem-64215.appspot.com',
    iosClientId: '832641360790-i3pv3uqh4q0tr22eriubmkej5610gh42.apps.googleusercontent.com',
    iosBundleId: 'com.example.croosflatformpos',
  );
}
